### ISSUE TITLE
add 'adminer' for simple database management

### ISSUE THREAD

**Issue by awchjimmy** [awchjimmy/good-old-memories-v62#5]
add 'adminer' for simple database management

1. Check if everything works fine.
2. Simple database management.

**Comment by awchjimmy** [comment]
Since the commit is a mess, I'll try to extract the key part:

## modify `docker-compose.yml`
```yml
services:
  dbserver:
    image: mysql:5.7.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragezone
      MYSQL_DATABASE: XiuzSource
    volumes:
      - ./db/XiuzSource.sql:/docker-entrypoint-initdb.d/XiuzSource.sql
      - v62-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:5
    restart: always
    ports:
      - 8080:8080
```

## start service
```sh
docker compose up adminer
```

## visit browser
http://localhost:8080/

Done 🔥🔥🔥
